### ISSUE TITLE
Tracking custom entities

### ISSUE THREAD

**Issue by JoyMonteiro** [hguo/ftk#23]
Hello,

I recently came across this project, and it looks quite interesting! 

We have developed a methodology to identify certain features in climate data
https://bitbucket.org/vgl_iisc/rossby-wave-packet-identification/src/master/

and we would like to see if we could use ftk to track the features we identify.
Unlike the typical use-case that ftk describes in the accompanying paper,
our objects comprises of multiple critical points per feature. (See Figure 2
in [our paper](https://journals.ametsoc.org/doi/abs/10.1175/MWR-D-20-0014.1))

Does FTK have an API to which we can provide the features we identify (typically
clusters of critical points or graphs) and track them across time?

TIA,
Joy

**Comment by hguo** [comment]
Hi Joy,

Thanks for the comments.  I took a look at your paper and the code; they look very interesting! 

The short answer to your question is no.  FTK currently only supports the tracking of features that are defined locally and can detect within individual mesh cells.  For complex feature descriptors based on clustering and non-local information, there is no straightforward way to track them. 

Being said, it might be possible to generalize your algorithm to filter and cluster trajectories of critical points, as opposed to discrete critical points in individual timesteps.  In this scenario, FTK provides APIs to compute trajectories, and one can further process trajectories in post-processing.  There may be some amount of work involved, but it seems to be an interesting research topic.

Best,
Hanqi

**Comment by JoyMonteiro** [comment]
Thanks for your suggestions, Hanqi! I will close this issue for now and write back if we manage to make
further progress.
